default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: CISCOPHRENZYa1
  host: localhost

development:
  <<: *default
  database: y_recipes
  username: postgres
  password: CISCOPHRENZYa1
  host: localhost
  port: 5432

test:
  <<: *default
  database: y_recipes_test
  username: postgres
  password: CISCOPHRENZYa1

production:
  <<: *default
  database: y_recipes_production
  username: y_recipes_user
  password: <%= ENV['Y_RECIPES_DATABASE_PASSWORD'] %>
  host: <%= ENV['Y_RECIPES_DATABASE_HOST'] %>
